---
title: "efa`"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    df_print: kable
    code_folding: hide
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 5
    number_sections: yes
    highlight: tango
    fig_width: 12
    fig_height: 12
  word_document:
    toc: yes
    toc_depth: '5'
header-includes: \usepackage{float} \floatplacement{figure}{H} \usepackage{longtable}
---

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set( -->
<!--   echo = T,  -->
<!--   comment = "#>", -->
<!--   results = "hide",  -->
<!--   message = FALSE, -->
<!--   warning = FALSE, -->
<!--   tidy.opts = list(width.cutoff=60) -->
<!--   ) -->
<!-- ``` -->

## `r x`-Factor Extraction {.tabset .tabset-fade}
### Loadings
```{r factor-analysis-loadings, results = "asis", error = TRUE}
efa <- EFA(
  pcor, 
  n_factors = x, 
  rotation = "promax",
  N = nrow(efa_df) # N observations
  )

floads <- efa$rot_loadings %>% unclass
fnames <- glue("F{1:ncol(floads)}")

floads %>% 
  round(2) %>% 
  datatable(
    .,
    extensions = 'FixedColumns',
    options = list(
      dom = 'rt',
      scrollX = TRUE,
      fixedColumns = TRUE,
      pageLength = ncol(pcor),
      scrollY = 500,
      scroller = TRUE
    ),
    rownames = TRUE
  ) %>% formatStyle(
    columns = fnames,
    backgroundColor = styleInterval(0.29, c('gray', 'orange'))
  ) %>% formatStyle(
    columns = fnames,
    backgroundColor = styleInterval(-0.29, c('orange', 'NULL'))
  ) 
```
### Intercorrelations

```{r factor-analysis-intercorrelations, results = "asis", error = TRUE}
## Factor Intercorrelations
efa$Phi %>% 
  round(2) %>% 
  as_tibble() %>% 
  setNames(fnames) %>% 
  datatable(
    options = list(dom = 't', ordering = FALSE),
    rownames = fnames
    )
 
```

### Variances Accounted for

```{r factor-analysis-variances, results = "asis", error = TRUE}

efa$vars_accounted %>% 
  round(2) %>% 
  datatable(options = list(dom = 't', ordering = FALSE))

```

### Fit Indices and Settings
```{r factor-analysis-indices, results='asis', error = TRUE}
fiti <- efa$fit_indices 

tibble(
  " " = names(fiti),
  "Value"  = fiti %>% unlist %>% round(2)
  ) %>% 
  filter(!is.na(Value))
```

```{r factor-analysis-settings, results='asis', error = TRUE}
  
fits <- efa$settings 

tibble(
  Setting = names(fits),
  Value = fits %>% unlist
)

```