---
title: "Item Legends"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: yes
    df_print: kable
    code_folding: hide
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 5
    number_sections: yes
    highlight: tango
    fig_width: 12
    fig_height: 12
  word_document:
    toc: yes
    toc_depth: '5'
header-includes: \usepackage{float} \floatplacement{figure}{H} \usepackage{longtable}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = T, 
  comment = "#>",
  results = "hide", 
  message = FALSE,
  warning = FALSE,
  tidy.opts = list(width.cutoff=60)
  )
```

```{r setup-import}
library(here)
source(here("R", "helper_rmd-sources.R"))

legend <- cd %>% 
  rename (
  "Label" = labels,
  "Item" = qualtrics,
  ) %>% 
  mutate(
    Reverse = case_when(
      Label %in% hte_to_reverse ~"Yes",
      TRUE ~ "No"
    )
  ) %>% 
  select(- cols, - question)

hte_legend <- tibble(
  "Label" = hte_labels,
  "Item" = hte_cols %>% snake_to_sentence %>% {str_glue("{.}.")}
  ) %>% 
  mutate(
    Reverse = case_when(
      Label %in% hte_to_reverse ~"Yes",
      TRUE ~ "No"
    )
  )

```
## Legends for Items {.tabset .tabset-fade}

### How To Eat 

```{r results = "asis"}
hte_legend %>% 
  datatable(
    rownames = FALSE
    )

```

### Food Literacy and Newest Vital Sign


```{r results = "asis"}
legend %>% 
  datatable(
    rownames = FALSE,
    extensions = "Buttons",
    options = list(
      columnDefs = list(
        list(visible = FALSE, 
             targets = -1 + which(
              !names(legend) %in% c("Label", "Item")
              ) 
             )
        ),
      dom = 'Bfrtip',
      buttons = c('colvis', 'excel')
    )
  )

```