---
title: "Theory"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: kable
    code_folding: hide
  pdf_document: 
    latex_engine: xelatex
    toc: true
    toc_depth: 5
    number_sections: true
    highlight: tango
    fig_width: 12
    fig_height: 12
header-includes:
   \usepackage{float}
    \floatplacement{figure}{H}
    \usepackage{longtable}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message= F, warning = F, comment=NA, results = "hide", tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

 Definitions

- True test score: Expectation of test score; error-free.
- Parallel tests: Independent repetitions of the same test. In general the test scores will not be equal due to random measurement error.
- Reliability (3 Ways to Describe): 
   + Pearson's correlation between parallel test scores.
   + The ratio of true score and test score variances.
   + 1 minus the ratio of error and test score variances.
- Essential Tau (Test Score)-Equivalence: Between any two items, the true score of one is equal to the true score of another plus some constant. Since the covariance of a random variable with a constant is zero, this implies that 
  + Interitem covariance is the same between any two items.
  + Item covariance is the same for all items.


Alpha is only equal to reliability if and only if items are essentially tau-equivalent.

"Like parallelism, essential τ -equivalence is not a realistic condition in test
data, so that in real data we have that alpha < reliability." 

Sijtsma, K. (2009). On the use, the misuse, and the very limited usefulness of Cronbach’s alpha. Psychometrika, 74(1), 107.
