library(ICCbin)
library(irr)
library(fs)
library(gt)
library(DT)
library(GPArotation)
library(Rcsdp)
library(snakecase)
library(here)
library(tidyverse)
library(vroom)
library(janitor)
library(glue)
library(gtsummary)
library(corrr)
library(polycor)
library(EFA.dimensions)
library(EFAtools)
library(evaluate)
library(readxl)
library(qualtRics)
library(sjlabelled)
library(gridExtra)
library(reactable)
library(kableExtra)

## also using through ::
## XLConnect as it has Java conflicts with readr
## fread :: 
## webshot::install_phantomjs()
## evaluate::evaluate()
#renv::init()
#renv::snapshot()
